logging.level:
    org.hibernate.tool.hbm2ddl: INFO
    org.hibernate.SQL: INFO
  
spring:
    dataSource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/iblog
        username: root
        password: root

    hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
        show_sql: true